# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsContributionExtractor < Formula
  desc "Jenkins Contribution data extractor and analyzer."
  homepage "https://github.com/jenkins-infra/jenkins-contribution-extractor"
  version "0.2.18"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jenkins-infra/jenkins-contribution-extractor/releases/download/v0.2.18/jenkins-contribution-extractor_0.2.18_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c4557cc3b68216e660a318d6baabbf9a65dcbc70bb59310cb7b30a6ff4e8af12"

      def install
        bin.install "jenkins-contribution-extractor"
      end
    end
    on_arm do
      url "https://github.com/jenkins-infra/jenkins-contribution-extractor/releases/download/v0.2.18/jenkins-contribution-extractor_0.2.18_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7bc245d8b2df49b45c7138fb0ab51104841cf5c8b6e4915ad662cbebcc29361c"

      def install
        bin.install "jenkins-contribution-extractor"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jenkins-infra/jenkins-contribution-extractor/releases/download/v0.2.18/jenkins-contribution-extractor_0.2.18_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "bf3a38597672815c926efb6c4b63240dfe51a526b49354292c97a97364d99c98"

        def install
          bin.install "jenkins-contribution-extractor"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/jenkins-infra/jenkins-contribution-extractor/releases/download/v0.2.18/jenkins-contribution-extractor_0.2.18_linux_armv6.tar.gz", using: CurlDownloadStrategy
        sha256 "f92c925eefd490abeb011133f7bd969538a1c12dbbe3836ae7049b6decd84ac4"

        def install
          bin.install "jenkins-contribution-extractor"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jenkins-infra/jenkins-contribution-extractor/releases/download/v0.2.18/jenkins-contribution-extractor_0.2.18_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "b6f839bec6ed449739c796e97dc2c0808e8d9a9976d03abc66e4559aefe76b1e"

        def install
          bin.install "jenkins-contribution-extractor"
        end
      end
    end
  end

  test do
    system "#{bin}/jenkins-contribution-extractor version -d"
  end
end
