# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jv < Formula
  desc "Determine a Jenkins Version"
  homepage "https://github.com/jenkins-infra/jenkins-version"
  version "0.11.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jenkins-infra/jenkins-version/releases/download/0.11.3/jenkins-version-darwin-amd64.tar.gz"
      sha256 "71d98fe706f3f65d6537ead1db1d71aef6dc5ab9a33fa6283ab20389e371edd8"

      def install
        bin.install "jv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jenkins-infra/jenkins-version/releases/download/0.11.3/jenkins-version-darwin-arm64.tar.gz"
      sha256 "4d2cb2cb3f0c1a4ef989d45216a566c11b550efc140bbd6bcab51b0dfd9fced2"

      def install
        bin.install "jv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jenkins-infra/jenkins-version/releases/download/0.11.3/jenkins-version-linux-amd64.tar.gz"
      sha256 "a7033749dd0d27b55a3dc3cc9cf92dd12b47910013e9fa6a4d4dff689eab69d0"
      def install
        bin.install "jv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jenkins-infra/jenkins-version/releases/download/0.11.3/jenkins-version-linux-arm64.tar.gz"
      sha256 "ed83d4494b21f8f6f54e98cff808f163623d6140fe0ddd40ae1cb457a000c22d"
      def install
        bin.install "jv"
      end
    end
  end
end
