# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uc < Formula
  desc "Utility to update jenkins plugin.txt"
  homepage ""
  version "0.1.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jenkins-infra/uc/releases/download/0.1.3/uc-darwin-amd64.tar.gz"
      sha256 "473ba5d706359b518bd66ca919d36c0a7155d50933643263919225411e3731bf"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jenkins-infra/uc/releases/download/0.1.3/uc-darwin-arm64.tar.gz"
      sha256 "637d6ae8fc17c21327f44be93f8114691677310955b90463712eba0ab02eeabd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jenkins-infra/uc/releases/download/0.1.3/uc-linux-amd64.tar.gz"
      sha256 "1cb11b7e76dbc6c271d2fca659a6c6d6fc8e126ded78dc1edd175027e4099b5c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jenkins-infra/uc/releases/download/0.1.3/uc-linux-arm64.tar.gz"
      sha256 "ae92bd665dc3cc2e9ca0718707052e35e4f58d3155fd740744a478269303473e"
    end
  end

  def install
    bin.install "uc"
  end
end
